# Temporary for the branch-deploy until the PR is merged and build command updated in app console
[context.deploy-preview]
  command = "npm run build && cp -v dist/* example/ && node ./scripts/build-command.js"
